live_config_reload = true
working_directory = "None"

[colors.bright]
black = "#6d6c6f"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#ff5370"
white = "#eeffff"
yellow = "#ffcb6b"

[colors.cursor]
cursor = "#ffcb6b"
text = "#090b10"

[colors.normal]
black = "#0f111a"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#ff5370"
white = "#eeffff"
yellow = "#ffcb6b"

[colors.primary]
background = "#0f111a"
foreground = "#eeffff"

[colors.selection]
background = "#6f7cbf"
text = "#ffffff"

[cursor.style]
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.bold]
family = "FiraCode NF"
style = "Bold"

[font.bold_italic]
family = "FiraCode NF"
style = "Bold Italic"

[font.italic]
family = "FiraCode NF"
style = "Italic"

[font.normal]
family = "FiraCode NF"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Shift|Control"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.97
startup_mode = "Windowed"

[window.padding]
x = 4
y = 4
