require("config.user.options")
require("config.user.colorscheme") -- comes after options to overwrite them (set transparent background)
require("config.user.auto_commands")
require("config.user.keymaps")
require("config.user.macros")
require("config.user.netrw")
