return {
  "WhoIsSethDaniel/mason-tool-installer.nvim", -- automatic third party tooling installation (through mason)
  dependencies = { "williamboman/mason.nvim" },
  opts = {
    ensure_installed = {
      "stylua",
      "shfmt",
      "prettierd",
      "latexindent",
      "phpstan",
      "vim-language-server",
      "typescript-language-server",
      "bash-language-server",
      "css-lsp",
      "cssmodules-language-server",
      "dockerfile-language-server",
      "html-lsp",
      "json-lsp",
      "marksman",
      "sqlls",
      "lemminx",
      "yaml-language-server",
      "phpactor",
      "clangd",
      "pyright",
      "eslint-lsp",
      "emmet-ls",
      "ruff",
      "lua-language-server",
      "rust-analyzer",
      "taplo",
      -- "clang-format", -- use binary from PATH to ensure formatting consistency across nvim and other tooling
    },
  },
}
